# Generated by Django 3.1.2 on 2020-10-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de cuando el objecto fue creado', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de cuando el objecto fue modificado', verbose_name='Modificado el')),
                ('speciality', models.CharField(max_length=100, verbose_name='Especialidad')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
