# Generated by Django 3.1.2 on 2020-10-15 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacient', '0001_initial'),
        ('medic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='pacients',
            field=models.ManyToManyField(through='pacient.Pacient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
