# Generated by Django 3.1.2 on 2020-10-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0002_pacient_user'),
        ('medic', '0002_auto_20201015_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de cuando el objecto fue creado', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de cuando el objecto fue modificado', verbose_name='Modificado el')),
                ('final_date_inability', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.medic')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacient.pacient')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de cuando el objecto fue creado', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de cuando el objecto fue modificado', verbose_name='Modificado el')),
                ('exam_name', models.CharField(max_length=50)),
                ('description_exam', models.TextField(max_length=500)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacient.pacient')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
