# Generated by Django 3.1.2 on 2020-10-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAppoinmentModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de cuando el objecto fue creado', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de cuando el objecto fue modificado', verbose_name='Modificado el')),
                ('date_appoinment', models.DateField()),
                ('url_webex', models.URLField()),
                ('symptoms', models.TextField(max_length=250)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.medic')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
