# Generated by Django 3.1.2 on 2020-10-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_appoinment', '0001_initial'),
        ('pacient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappoinmentmodels',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacient.pacient'),
        ),
    ]
