# Generated by Django 3.1.2 on 2020-10-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de cuando el objecto fue creado', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de cuando el objecto fue modificado', verbose_name='Modificado el')),
                ('slug_name', models.CharField(max_length=25)),
                ('family_limit', models.PositiveIntegerField(default=5, help_text='Los grupos familiares estan limitados a 5 familiares incluyendo al titular')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de cuando el objecto fue creado', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de cuando el objecto fue modificado', verbose_name='Modificado el')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Titular')),
                ('affiliated', models.PositiveIntegerField(default=0)),
                ('remaining_affiliates', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
