# Generated by Django 3.1.2 on 2020-10-15 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family_group', '0001_initial'),
        ('pacient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberships',
            name='affiliated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberships',
            name='family_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_group.familygroup'),
        ),
        migrations.AddField(
            model_name='memberships',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacient.pacient'),
        ),
        migrations.AddField(
            model_name='memberships',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familygroup',
            name='members',
            field=models.ManyToManyField(through='family_group.Memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
